# default: &default
#   adapter: 'sqlite3'
#   database: 'db/development.sqlite'

# development:
#   <<: *default

# test:
#   <<: *default
#   database: 'db/test.sqlite'

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: krane_development

test:
  <<: *default
  database: krane_test

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
