# default: &default
#   adapter: 'sqlite3'
#   database: 'db/development.sqlite'

# development:
#   <<: *default

# test:
#   <<: *default
#   database: 'db/test.sqlite'

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  # <<: *default
  adapter: postgresql
  encoding: unicode
  database: krane_development
  pool: 2
  username: ckingsley
  password: supersecuredatabasepassword

# test:
#   <<: *default
#   database: krane_test

production:
  # <<: *default
   adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
